#Deployment
apiVersion: batch/v1
kind: dep
metadata:
  name: docker-products-dep
  #namespace: task
  labels:
    app: docker-products
spec:
    #selector:
    #matchLabels:
      #app: docker-products
  template:
    metadata:
      labels:
        app: docker-products
    spec:
      restartPolicy: OnFailure  # Always
      containers:
      - name: docker-products
        image: gautam1998/docker-products:v1.0.0
        ports:
        - containerPort: 8080
        resources:
         limits:
           memory: 512Mi
           cpu: "1"
         requests:
           memory: 256Mi
           cpu: "0.2"
---
#service
apiVersion: v1
kind: Service
metadata:
  name: docker-products-svc
  #namespace: task
  labels:
    app: docker-products
spec:
  selector:
    app: docker-products
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port
